using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardsDirector : MonoBehaviour
{
    [SerializeField] List<GameObject> prefabSpades;
    [SerializeField] List<GameObject> prefabClubs;
    [SerializeField] List<GameObject> prefabDiamonds;
    [SerializeField] List<GameObject> prefabHearts;
    [SerializeField] List<GameObject> prefabJokers;

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }
    //ã‚·ãƒ£ãƒƒãƒ•ãƒ«ã—ãŸã‚«ãƒ¼ãƒ‰ã‚’è¿”ã™
    public List<CardController> GetShuffleCards()
    {
        List<CardController> ret = new List<CardController>();

        ret.AddRange(createCards(SuitType.Spade));
        ret.AddRange(createCards(SuitType.Club));
        ret.AddRange(createCards(SuitType.Diamond));
        ret.AddRange(createCards(SuitType.Heart));

        ShuffleCards(ret);

        return ret;
    }
    //ç¥çµŒè¡°å¼±ã§ä½¿ã†ã‚«ãƒ¼ãƒ‰ã‚’è¿”ã™
    public List<CardController> GetMemoryCards()
    {
        List<CardController> ret = new List<CardController>();

        ret.AddRange(createCards(SuitType.Spade, 10));
        ret.AddRange(createCards(SuitType.Diamond, 10));

        ShuffleCards(ret);

        return ret;
    }    //ã‚·ãƒ£ãƒƒãƒ•ãƒ«
    public void ShuffleCards(List<CardController> cards)
    {
        for (int i = 0; i < cards.Count; i++)
        {
            int rnd = Random.Range(0, cards.Count);
            CardController tmp = cards[i];

            cards[i] = cards[rnd];
            cards[rnd] = tmp;
        }
    }

    //ã‚«ãƒ¼ãƒ‰ä½œæˆ
    List<CardController> createCards(SuitType suittype, int count = -1)
    {
        List<CardController> ret = new List<CardController>();

        //ã‚«ãƒ¼ãƒ‰ã®ç¨®é¡ï¼ˆãƒ‡ãƒ•ã‚©ãƒ«ãƒˆï¼‰
        List<GameObject> prefabcards = prefabSpades;
        Color suitcolor = Color.black;

        if (SuitType.Club == suittype)
        {
            prefabcards = prefabClubs;
        }
        else if (SuitType.Diamond == suittype)
        {
            prefabcards = prefabDiamonds;
            suitcolor = Color.red;
        }
        else if (SuitType.Heart == suittype)
        {
            prefabcards = prefabHearts;
            suitcolor = Color.red;
        }
        else if (SuitType.Joker == suittype)
        {
            prefabcards = prefabJokers;
        }
        //æšæ•°ã«æŒ‡å®šãŒãªã‘ã‚Œã°å…¨ã¦ã®ã‚«ãƒ¼ãƒ‰ã‚’ä½œæˆã™ã‚‹
        if (0 > count)
        {
            count = prefabcards.Count;
        }

        //ã‚«ãƒ¼ãƒ‰ç”Ÿæˆ
        for (int i = 0; i < count; i++)
        {
            GameObject obj = Instantiate(prefabcards[i]);

            //å½“ãŸã‚Šåˆ¤å®šè¿½åŠ 
            BoxCollider bc = obj.AddComponent<BoxCollider>();
            //å½“ãŸã‚Šåˆ¤å®šæ¤œçŸ¥ç”¨
            Rigidbody rb = obj.AddComponent<Rigidbody>();
            //ã‚«ãƒ¼ãƒ‰åŒå£«ã®å½“ãŸã‚Šåˆ¤å®šã¨ç‰©ç†æ¼”ç®—ã‚’ä½¿ã‚ãªã„
            bc.isTrigger = true;
            rb.isKinematic = true;

            //ã‚«ãƒ¼ãƒ‰ã«ãƒ‡ãƒ¼ã‚¿ã‚’ã‚»ãƒƒãƒˆ
            CardController ctrl = obj.AddComponent<CardController>();

            ctrl.Suit = suittype;
            ctrl.SuitColor = suitcolor;
            ctrl.PlayerNo = -1;
            ctrl.No = i + 1;

            ret.Add(ctrl);
        }

        return ret;

    }

}
/*
List<CardController>
:CardControllerã‚¯ãƒ©ã‚¹ã§å®šç¾©ã—ãŸã‚‚ã®ã‚’ä½¿ãˆã‚‹ãƒªã‚¹ãƒˆ
CardControllerã‚¯ãƒ©ã‚¹ã«ã¯ã€Suitï¼ˆãƒãƒ¼ã‚¯ï¼‰ã¨ã‹Noï¼ˆç•ªå·ï¼‰ã¨ã‹FlipCard()ï¼ˆã‚ãã‚‹å‡¦ç†ï¼‰ã¨ã‹ãŒå®šç¾©ã•ã‚Œã¦ã‚‹ã‚ˆãªï¼Ÿ
List<CardController>ã£ã¦ã„ã†ã®ã¯ã€**ãã®å…¨éƒ¨ã®æ©Ÿèƒ½ã‚„ãƒ‡ãƒ¼ã‚¿ã‚’æŒã£ãŸã€Œã‚«ãƒ¼ãƒ‰1æšåˆ†ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã€**ã‚’ã¾ã¨ã‚ã¦ç®¡ç†ã™ã‚‹ãŸã‚ã®ãƒªã‚¹ãƒˆã€‚
ã ã‹ã‚‰ã€ãã®ãƒªã‚¹ãƒˆã‹ã‚‰å–ã‚Šå‡ºã—ãŸ1æšã¯ã“ã†ã„ã†é¢¨ã«ä½¿ãˆã‚‹ğŸ‘‡
cards[0].Suit = SuitType.Heart;   // 0ç•ªç›®ã®ã‚«ãƒ¼ãƒ‰ã®ãƒãƒ¼ã‚¯ã‚’ãƒãƒ¼ãƒˆã«ã™ã‚‹
cards[0].FlipCard(true);          // 0ç•ªç›®ã®ã‚«ãƒ¼ãƒ‰ã‚’è¡¨ã«ã™ã‚‹

ã“ã®ã‚¹ã‚¯ãƒªãƒ—ãƒˆã§ã‚„ã£ã¦ã‚‹ã“ã¨
ã“ã®ã‚³ãƒ¼ãƒ‰ã¯ã¾ãš createCards é–¢æ•°ã§ã€æŒ‡å®šã•ã‚ŒãŸãƒãƒ¼ã‚¯ï¼ˆSuitTypeï¼‰ã«å¿œã˜ã¦ã€å¯¾å¿œã™ã‚‹ã‚«ãƒ¼ãƒ‰Prefabã‚’è¤‡è£½ã—ã¦ CardController å‹ã®ãƒªã‚¹ãƒˆ ret ã‚’ä½œã‚Šè¿”ã™ã€‚
ãã®å¾Œã€ã“ã®ãƒªã‚¹ãƒˆã‚’ ShuffleCards é–¢æ•°ã«æ¸¡ã™ã“ã¨ã§ã€åŒã˜ã‚«ãƒ¼ãƒ‰ãŒé‡è¤‡ã—ãªã„ã‚ˆã†é †ç•ªã‚’ãƒ©ãƒ³ãƒ€ãƒ ã«ä¸¦ã¹æ›¿ãˆ


ShuffleCardsé–¢æ•°ã«æ¸¡ã›ã¦ã‚‹ï¼Ÿå…¨éƒ¨ãŒã†ã¾ã„ã“ã¨æ©Ÿèƒ½ã—ã¦ã‚‹ã‹ç–‘å•
*/
